const hre = require("hardhat");
const path = require("path");
const fs   = require("fs");

/**
 * deploy-intent.js
 *
 * Deploys IntentForge.sol and auto-writes the contract address + ABI into
 *   ../src/config/contracts.js
 * so the React frontend is always in sync without manual copy-paste.
 *
 * Run:
 *   npx hardhat run scripts/deploy-intent.js --network localhost
 */
async function main() {
  console.log("\n🚀 Deploying IntentForge (Role-Based Fund Contract)...\n");

  // ── Account layout ───────────────────────────────────────────────
  const signers = await hre.ethers.getSigners();
  const lender   = signers[0];   // Account 0 — Rule Imposer
  const receiver = signers[1];   // Account 1 — Restricted User

  console.log("📋 Role Configuration:");
  console.log("├─ Lender   (Account 0):", lender.address);
  console.log("└─ Receiver (Account 1):", receiver.address);
  console.log();

  // ── Deploy ────────────────────────────────────────────────────────
  const IntentForge = await hre.ethers.getContractFactory("IntentForge");
  const contract    = await IntentForge.deploy();
  await contract.waitForDeployment();

  const contractAddress = await contract.getAddress();
  console.log("✅ IntentForge deployed to:", contractAddress);
  console.log("✅ Network:", hre.network.name);
  console.log();

  // ── Load ABI from compiled artifact ──────────────────────────────
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/IntentForge.sol/IntentForge.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;

  // ── Write contracts.js for the React frontend ────────────────────
  const contractsConfigPath = path.join(
    __dirname,
    "../../src/config/contracts.js"
  );

  const configContent = `/* ─── Auto-generated by deploy-intent.js — do not edit manually ─── */
/* Last deployed: ${new Date().toISOString()} */

export const INTENT_FORGE_ADDRESS = "${contractAddress}";

export const LENDER_ADDRESS   = "${lender.address}";
export const RECEIVER_ADDRESS = "${receiver.address}";

export const CHAIN_ID = ${hre.network.config.chainId || 31337};
export const RPC_URL  = "http://127.0.0.1:8545";

export const INTENT_FORGE_ABI = ${JSON.stringify(abi, null, 2)};
`;

  fs.writeFileSync(contractsConfigPath, configContent, "utf8");
  console.log("📝 Frontend config written to src/config/contracts.js");
  console.log();

  // ── Summary ────────────────────────────────────────────────────────
  console.log("🎯 Deployment Summary");
  console.log("═══════════════════════════════════════════");
  console.log("Contract  :", contractAddress);
  console.log("Lender    :", lender.address);
  console.log("Receiver  :", receiver.address);
  console.log("Network   :", hre.network.name);
  console.log("Chain ID  :", hre.network.config.chainId || 31337);
  console.log("═══════════════════════════════════════════");
  console.log();
  console.log("Next steps:");
  console.log("  1. Import Account 0 & Account 1 into MetaMask");
  console.log("     RPC: http://127.0.0.1:8545  |  Chain ID: 31337");
  console.log("  2. npm start  (frontend already has the new address)");
  console.log("  3. Open http://localhost:3000/intent");
  console.log();
  console.log("✅ Ready to demo!\n");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("❌ Deploy failed:", err);
    process.exit(1);
  });
